# Generated by Django 4.1.7 on 2023-04-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип чая', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/')),
                ('name', models.CharField(help_text='Введите название чая', max_length=60)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Доступен'), ('n', 'Нет в наличии')], default='a', help_text='Наличие чая', max_length=1)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teazen.product')),
            ],
        ),
    ]
