# Generated by Django 4.1.7 on 2023-04-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
