# Generated by Django 4.1.7 on 2023-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0005_cart_cartitem_delete_order_cart_products_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
