# Generated by Django 4.1.7 on 2023-04-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0011_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
