# Generated by Django 4.1.7 on 2023-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0012_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
