# Generated by Django 4.1.7 on 2023-04-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0015_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', to='teazen.orderitem'),
        ),
    ]
