# Generated by Django 4.1.7 on 2023-04-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0016_alter_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
