# Generated by Django 4.1.7 on 2023-04-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0017_remove_order_order_items_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='teazen.order'),
            preserve_default=False,
        ),
    ]
