# Generated by Django 4.1.7 on 2023-04-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teazen', '0018_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
